object Versions {
    const val material3 = "1.1.2"
    const val junit = "4.13.2"
    const val andoridJunit = "1.1.5"
    const val espressoCore = "3.5.1"
    const val coreKtx = "1.12.0"
    const val navigationCompose = "2.7.4"
    const val debugUiTestManifest = "1.5.4"
    const val lifecycleRuntimeKtx = "2.6.2"
    const val activityCompose = "1.8.0"
    const val composeBom = "2023.10.01"
    const val appcompat = "1.6.1"
    const val composeUi = "1.5.4"
    const val room = "2.5.0"
    const val hilt = "2.44"
    const val hiltNavigationCompose = "1.0.0"
    const val coil = "2.5.0"
    const val mmkv = "1.3.1"
    const val splashscreen = "1.0.0"
    const val okHttp = "4.11.0"
    const val browser = "1.5.0"
    const val moshi = "1.14.0"
    const val moshiKotlin = "1.14.0"
}